name: SystemInfo
main: com.github.neapovil.systeminfo.SystemInfo
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/systeminfo
depend:
  - CommandAPI
permissions:
  systeminfo.command:
    default: op
